# Build
FROM golang:1.25.3-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/main.go

# Runner    
FROM alpine:latest
WORKDIR /app
RUN apk --no-cache add ca-certificates poppler-utils tzdata

COPY --from=builder /app/server .
COPY --from=builder /app/config.json .

ENV PORT=8080
EXPOSE ${PORT}

CMD ["./server"]